GRANT ALL PRIVILEGES ON *.* TO 'test'@'localhost' IDENTIFIED BY 'some_pass' WITH GRANT OPTION;

create table CUSTOMER (CUST_ID char(20) PRIMARY KEY, FIRST_NAME char(20), LAST_NAME char(20), COUNTRY char(20));

create table CUST_BOOKMARK (CUST_ID char (20), BOOKMARK_LOCATION varchar(300), FOREIGN KEY (CUST_ID) REFERENCES CUSTOMER(CUST_ID) ON DELETE CASCADE);